services:
  backend:
    build: ./backend
    container_name: tienda-servicios-backend-1
    ports:
      - "${APP_PORT_BACK}"
    env_file: 
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ROLE_ADMIN_NAME=${ROLE_ADMIN_NAME}
      - ROLE_BASIC_NAME=${ROLE_BASIC_NAME}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BASIC_NAME=${BASIC_NAME}
      - BASIC_EMAIL=${BASIC_EMAIL}
      - BASIC_PASSWORD=${BASIC_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_SECRET_ID=${AWS_SECRET_ID}
    depends_on:
      - db
    networks:
      - ${NETWORK_NAME}

  db:
    image: ${IMGE_NAME}
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORTS}"
    volumes:
      - ${VOLUME_NAME}
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    driver: ${DRIVER_NAME}

volumes:
  ${DB_VOLUME_NAME}: 
